// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMkUMoLX2ikUj0e9n2ddrmxXSfJBNM95g',
    appId: '1:924604466216:web:0367479557e67d2a2f611d',
    messagingSenderId: '924604466216',
    projectId: 'noteapp-8d647',
    authDomain: 'noteapp-8d647.firebaseapp.com',
    storageBucket: 'noteapp-8d647.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30S2W55Ft_1eLMsw2Tb50xRzrduHVZQc',
    appId: '1:924604466216:android:d85c6e7bfbb4fbf32f611d',
    messagingSenderId: '924604466216',
    projectId: 'noteapp-8d647',
    storageBucket: 'noteapp-8d647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHcS-Ymo_CPL3Wj2h4tAE2LFwuvbZmAc',
    appId: '1:924604466216:ios:197780d4552452d72f611d',
    messagingSenderId: '924604466216',
    projectId: 'noteapp-8d647',
    storageBucket: 'noteapp-8d647.firebasestorage.app',
    iosBundleId: 'com.example.noteappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYHcS-Ymo_CPL3Wj2h4tAE2LFwuvbZmAc',
    appId: '1:924604466216:ios:197780d4552452d72f611d',
    messagingSenderId: '924604466216',
    projectId: 'noteapp-8d647',
    storageBucket: 'noteapp-8d647.firebasestorage.app',
    iosBundleId: 'com.example.noteappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMkUMoLX2ikUj0e9n2ddrmxXSfJBNM95g',
    appId: '1:924604466216:web:a16ee12dec7542fa2f611d',
    messagingSenderId: '924604466216',
    projectId: 'noteapp-8d647',
    authDomain: 'noteapp-8d647.firebaseapp.com',
    storageBucket: 'noteapp-8d647.firebasestorage.app',
  );
}
